### ISSUE TITLE
Published Paper jar crashes on pure Spigot since #998

### ISSUE THREAD

**Issue by HyacinthHaru** [WiIIiam278/HuskHomes#1005]
## Summary
Since the MiniMessage migration (#998, commit `dd2c453a`, merged 2026-07-13), the `HuskHomes-Paper-*.jar` artifact — which is also the file published for the `spigot` loader on Modrinth/Hangar — no longer contains the Adventure core classes it references, and nothing provides them on a pure Spigot server. The plugin should fail to enable there with a `NoClassDefFoundError` for `net/kyori/adventure/...` classes.
I found this via artifact inspection while preparing Paper 26.2 support, so this report is based on static evidence rather than a live crash log — it should be quick to confirm by starting a current alpha build on any pure Spigot server.

## Affected builds
All alpha-channel builds since 2026-07-13. Verified against `HuskHomes-Paper-4.11-ab42970.jar` downloaded from Modrinth (built from current master).

## Evidence
1. #998 added `shadowJar` dependency excludes in `paper/build.gradle` for `adventure-api`, `adventure-text-minimessage`, all serializers, `adventure-key`, etc., with the rationale "Paper provides Adventure API + MiniMessage natively". That is correct for Paper — but the same jar is what CI publishes for the `spigot` loader (`files-primary: target/HuskHomes-Paper-*.jar`, loaders `spigot | paper | folia`).
2. Inspecting the published jar: the only `net.kyori` classes remaining are the 111 entries under `net/kyori/adventure/platform/**` (adventure-platform-bukkit). No `adventure-api`, no MiniMessage, no serializers.
3. The `plugin.yml` inside the jar (the descriptor Spigot uses, `main: BukkitHuskHomes`) declares libraries: for Jedis and the JDBC drivers only — Adventure is not supplied via Spigot's library loader either.
4. Classes in the jar reference unrelocated `net.kyori.adventure` types throughout (`MiniMessage, Component, Title, Sound, …`), and on the Spigot path `BukkitHuskHomes#createAudiences()` calls `BukkitAudiences.create(...)` — the bundled adventure-platform-bukkit also cannot function without the excluded Adventure core.
5. Pure Spigot ships no Adventure at all → first touch of any of these classes throws `NoClassDefFoundError`.
Paper is unaffected: `paper-plugin.yml` takes precedence there, `PaperHuskHomes#createAudiences()` is a no-op, and the server provides Adventure natively.

## Suggested fix

Option A (minimal, keeps the Paper-native design): add the excluded Adventure artifacts (`adventure-api`, `adventure-text-minimessage`, the serializers used, pinned to 4.26.1) to `plugin.yml`'s libraries: so Spigot's library loader downloads them at runtime, exactly like the JDBC drivers. Paper ignores `plugin.yml` when `paper-plugin.yml` is present, so the Paper path stays on the server's native Adventure — which also matters for 26.2, where Paper ships Adventure 5.

Option B: publish the separate `HuskHomes-Bukkit` shadow jar (which bundles and relocates Adventure) as the Spigot artifact instead.

Happy to submit a PR for Option A if that direction sounds right — I'm currently working on Paper 26.2 support in the same area.
